import random, time
print('Advinhador de Números')
time.sleep(0.5)
print('Vou pensar em um número entre 1 e 5, e você tenta adivinhar')
time.sleep(1)
num = random.randint(0 , 5)
print('Pensando em um número...')
time.sleep(2)
adivinhação = int(input('Tente adivinhar qual numero pensei: '))
time.sleep(1)
print('Verificando...')
time.sleep(1)
print('Parabéns, você acertou!!!' if adivinhação == num else 'Que pena, você errou!')
time.sleep(0.5)
print('Eu pesei no número: {}'.format(num))
